import sys
import os
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Main(QtGui.QMainWindow):
    #signals

    QtCore.pyqtSignal()
    def __init__(self):
        super(Main,self).__init__()
        self.setupUi(MainWindow = self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(979, 791)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(700, 90, 161, 71))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.blinkButton = QtGui.QPushButton(self.centralwidget)
        self.blinkButton.setGeometry(QtCore.QRect(60, 100, 161, 61))
        self.blinkButton.setObjectName(_fromUtf8("blinkButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 60, 271, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.stopBlinkButton = QtGui.QPushButton(self.centralwidget)
        self.stopBlinkButton.setGeometry(QtCore.QRect(240, 100, 161, 61))
        self.stopBlinkButton.setObjectName(_fromUtf8("stopBlinkButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 161, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.helloButton = QtGui.QPushButton(self.centralwidget)
        self.helloButton.setGeometry(QtCore.QRect(60, 230, 161, 61))
        self.helloButton.setObjectName(_fromUtf8("helloButton"))
        self.set1Q1Button = QtGui.QPushButton(self.centralwidget)
        self.set1Q1Button.setGeometry(QtCore.QRect(250, 230, 71, 61))
        self.set1Q1Button.setObjectName(_fromUtf8("set1Q1Button"))
        self.set1A1Button = QtGui.QPushButton(self.centralwidget)
        self.set1A1Button.setGeometry(QtCore.QRect(330, 230, 71, 61))
        self.set1A1Button.setObjectName(_fromUtf8("set1A1Button"))
        self.set1Q2Button = QtGui.QPushButton(self.centralwidget)
        self.set1Q2Button.setGeometry(QtCore.QRect(250, 300, 71, 61))
        self.set1Q2Button.setObjectName(_fromUtf8("set1Q2Button"))
        self.set1A2Button = QtGui.QPushButton(self.centralwidget)
        self.set1A2Button.setGeometry(QtCore.QRect(330, 300, 71, 61))
        self.set1A2Button.setObjectName(_fromUtf8("set1A2Button"))
        self.set1Q3Button = QtGui.QPushButton(self.centralwidget)
        self.set1Q3Button.setGeometry(QtCore.QRect(250, 370, 71, 61))
        self.set1Q3Button.setObjectName(_fromUtf8("set1Q3Button"))
        self.set1A3Button = QtGui.QPushButton(self.centralwidget)
        self.set1A3Button.setGeometry(QtCore.QRect(330, 370, 71, 61))
        self.set1A3Button.setObjectName(_fromUtf8("set1A3Button"))
        self.set2A3Button = QtGui.QPushButton(self.centralwidget)
        self.set2A3Button.setGeometry(QtCore.QRect(560, 370, 71, 61))
        self.set2A3Button.setObjectName(_fromUtf8("set2A3Button"))
        self.set2Q3Button = QtGui.QPushButton(self.centralwidget)
        self.set2Q3Button.setGeometry(QtCore.QRect(480, 370, 71, 61))
        self.set2Q3Button.setObjectName(_fromUtf8("set2Q3Button"))
        self.set2Q1Button = QtGui.QPushButton(self.centralwidget)
        self.set2Q1Button.setGeometry(QtCore.QRect(480, 230, 71, 61))
        self.set2Q1Button.setObjectName(_fromUtf8("set2Q1Button"))
        self.set2A1Button = QtGui.QPushButton(self.centralwidget)
        self.set2A1Button.setGeometry(QtCore.QRect(560, 230, 71, 61))
        self.set2A1Button.setObjectName(_fromUtf8("set2A1Button"))
        self.set2Q2Button = QtGui.QPushButton(self.centralwidget)
        self.set2Q2Button.setGeometry(QtCore.QRect(480, 300, 71, 61))
        self.set2Q2Button.setObjectName(_fromUtf8("set2Q2Button"))
        self.set2A2Button = QtGui.QPushButton(self.centralwidget)
        self.set2A2Button.setGeometry(QtCore.QRect(560, 300, 71, 61))
        self.set2A2Button.setObjectName(_fromUtf8("set2A2Button"))
        self.set3A3Button = QtGui.QPushButton(self.centralwidget)
        self.set3A3Button.setGeometry(QtCore.QRect(790, 370, 71, 61))
        self.set3A3Button.setObjectName(_fromUtf8("set3A3Button"))
        self.set3Q3Button = QtGui.QPushButton(self.centralwidget)
        self.set3Q3Button.setGeometry(QtCore.QRect(710, 370, 71, 61))
        self.set3Q3Button.setObjectName(_fromUtf8("set3Q3Button"))
        self.set3Q1Button = QtGui.QPushButton(self.centralwidget)
        self.set3Q1Button.setGeometry(QtCore.QRect(710, 230, 71, 61))
        self.set3Q1Button.setObjectName(_fromUtf8("set3Q1Button"))
        self.set3A1Button = QtGui.QPushButton(self.centralwidget)
        self.set3A1Button.setGeometry(QtCore.QRect(790, 230, 71, 61))
        self.set3A1Button.setObjectName(_fromUtf8("set3A1Button"))
        self.set3Q2Button = QtGui.QPushButton(self.centralwidget)
        self.set3Q2Button.setGeometry(QtCore.QRect(710, 300, 71, 61))
        self.set3Q2Button.setObjectName(_fromUtf8("set3Q2Button"))
        self.set3A2Button = QtGui.QPushButton(self.centralwidget)
        self.set3A2Button.setGeometry(QtCore.QRect(790, 300, 71, 61))
        self.set3A2Button.setObjectName(_fromUtf8("set3A2Button"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 190, 71, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 190, 71, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 190, 71, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.musicSpeechButton = QtGui.QPushButton(self.centralwidget)
        self.musicSpeechButton.setGeometry(QtCore.QRect(70, 480, 161, 61))
        self.musicSpeechButton.setObjectName(_fromUtf8("musicSpeechButton"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 450, 201, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.playMusicButton = QtGui.QPushButton(self.centralwidget)
        self.playMusicButton.setGeometry(QtCore.QRect(250, 480, 161, 61))
        self.playMusicButton.setObjectName(_fromUtf8("playMusicButton"))
        self.stopMusicButton = QtGui.QPushButton(self.centralwidget)
        self.stopMusicButton.setGeometry(QtCore.QRect(430, 480, 161, 61))
        self.stopMusicButton.setObjectName(_fromUtf8("stopMusicButton"))
        self.bye3Button = QtGui.QPushButton(self.centralwidget)
        self.bye3Button.setGeometry(QtCore.QRect(430, 590, 161, 61))
        self.bye3Button.setObjectName(_fromUtf8("bye3Button"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 560, 71, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.bye1Button = QtGui.QPushButton(self.centralwidget)
        self.bye1Button.setGeometry(QtCore.QRect(70, 590, 161, 61))
        self.bye1Button.setObjectName(_fromUtf8("bye1Button"))
        self.bye2Button = QtGui.QPushButton(self.centralwidget)
        self.bye2Button.setGeometry(QtCore.QRect(250, 590, 161, 61))
        self.bye2Button.setObjectName(_fromUtf8("bye2Button"))
        self.finishButtton = QtGui.QPushButton(self.centralwidget)
        self.finishButtton.setGeometry(QtCore.QRect(710, 660, 161, 61))
        self.finishButtton.setObjectName(_fromUtf8("finishButtton"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, -10, 331, 61))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.blinkButton.setText(_translate("MainWindow", "Blink", None))
        self.label.setText(_translate("MainWindow", "Module 1 : Initial Response", None))
        self.stopBlinkButton.setText(_translate("MainWindow", "Stop", None))
        self.label_2.setText(_translate("MainWindow", "Module 2: Questions", None))
        self.helloButton.setText(_translate("MainWindow", "Hello!", None))
        self.set1Q1Button.setText(_translate("MainWindow", "Q1", None))
        self.set1A1Button.setText(_translate("MainWindow", "A1", None))
        self.set1Q2Button.setText(_translate("MainWindow", "Q2", None))
        self.set1A2Button.setText(_translate("MainWindow", "A2", None))
        self.set1Q3Button.setText(_translate("MainWindow", "Q3", None))
        self.set1A3Button.setText(_translate("MainWindow", "A3", None))
        self.set2A3Button.setText(_translate("MainWindow", "A3", None))
        self.set2Q3Button.setText(_translate("MainWindow", "Q3", None))
        self.set2Q1Button.setText(_translate("MainWindow", "Q1", None))
        self.set2A1Button.setText(_translate("MainWindow", "A1", None))
        self.set2Q2Button.setText(_translate("MainWindow", "Q2", None))
        self.set2A2Button.setText(_translate("MainWindow", "A2", None))
        self.set3A3Button.setText(_translate("MainWindow", "A3", None))
        self.set3Q3Button.setText(_translate("MainWindow", "Q3", None))
        self.set3Q1Button.setText(_translate("MainWindow", "Q1", None))
        self.set3A1Button.setText(_translate("MainWindow", "A1", None))
        self.set3Q2Button.setText(_translate("MainWindow", "Q2", None))
        self.set3A2Button.setText(_translate("MainWindow", "A2", None))
        self.label_3.setText(_translate("MainWindow", "Set 1", None))
        self.label_4.setText(_translate("MainWindow", "Set 2", None))
        self.label_5.setText(_translate("MainWindow", "Set 3", None))
        self.musicSpeechButton.setText(_translate("MainWindow", "Speech", None))
        self.label_6.setText(_translate("MainWindow", "Module 3: PLay Music", None))
        self.playMusicButton.setText(_translate("MainWindow", "Play", None))
        self.stopMusicButton.setText(_translate("MainWindow", "Stop", None))
        self.bye3Button.setText(_translate("MainWindow", "Bye3", None))
        self.label_7.setText(_translate("MainWindow", "Good Bye", None))
        self.bye1Button.setText(_translate("MainWindow", "Bye1", None))
        self.bye2Button.setText(_translate("MainWindow", "Bye2", None))
        self.finishButtton.setText(_translate("MainWindow", "Finish", None))
        self.label_8.setText(_translate("MainWindow", "SOCIAL ROBOT CONTROL INTERFACE", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3", None))
